#! /usr/bin/env python3

from PoloConfig import PoloConfig
from PoloMallet import PoloMallet
from PoloCorpus import PoloCorpus
import argparse

if __name__ == '__main__':

    # Main parser app
    parser = argparse.ArgumentParser(description='Welcome to Polo')
    parser.add_argument("--ini", help="Path to ini file (default: ./config.ini)", action="store", default='./config.ini')

    # Subparsers for specific activities
    subparsers = parser.add_subparsers(title="Actions", help='Select an action', dest='cmd')

    # SETUP
    parser_setup = subparsers.add_parser('setup', help='Set up a project directory')

    # INFO
    parser_info = subparsers.add_parser('info', help='Get project info')
    parser_info.add_argument('item', choices=['trials', 'mallet', 'nltk'])

    # CORPUS
    parser_corpus = subparsers.add_parser('corpus', help='Generates a corpus db')

    # MALLET
    parser_mallet = subparsers.add_parser('mallet', help='Runs mallet based on ini and saves to db')
    parser_mallet.add_argument('trial', help="Trial name (see ini)", action="store", type=str, nargs='?', default=None)
    parser_mallet.add_argument('-t', "--topics", help="Number of topics (override ini)", action="store", type=int)
    parser_mallet.add_argument('-i', "--iters", help="Number of iterations (override ini)", action="store", type=int)

    # Run the app
    args = parser.parse_args()

    if args.cmd == 'corpus':

        print("Import config")
        config = PoloConfig(args.ini)

        print("Initialize corpus")
        corpus = PoloCorpus(config)
        corpus.cache_mode = True

        print("Importing stopwords")
        corpus.import_table_stopword(use_nltk=True)

        print("Importing doc")
        corpus.import_table_doc()

        print("Importing doctoken")
        corpus.add_table_doctoken()

        print("Importing token")
        corpus.add_table_token()

        print("Importing bigrams")
        corpus.add_tables_ngram_and_docngram(n=2)

    elif args.cmd == 'mallet':

        print("Import config")
        config = PoloConfig(args.ini)

        this_trial = ''
        if args.trial:
            this_trial = args.trial
        else:
            trials = config.get_trial_names()
            this_trial = trials[0]

        #config.import_ini(this_trial)

        print("Initializing mallet for {}".format(this_trial))
        mallet = PoloMallet(config, this_trial)
        mallet.cache_mode = True

        print('Importing corpus')
        mallet.mallet_import()

        print('Training model')
        mallet.mallet_train()

        print("Putting data into database")
        mallet.tables_to_db()

        print("Adding diagnostics tables")
        mallet.add_diagnostics()

        print("Adding doc table with topic entropy")
        mallet.add_topic_entropy()

        print("Adding topicpair table")
        mallet.create_table_topicpair()

        print("Cleaning up")
        mallet.del_mallet_files()

        print("Done with", mallet.config.trial_name)

    elif args.cmd == 'info':

        if args.item == 'trials':
            config = PoloConfig(args.ini)
            trials = config.get_trial_names()
            # GET MORE INFO TO SHOW, e.g. num topics, etc.
            print('TRIALS:\n', '\n'.join(trials))


