#! /usr/bin/env python3

from PoloConfig import PoloConfig
from PoloMallet import PoloMallet
from PoloCorpus import PoloCorpus

if __name__ == '__main__':
    
    print("Welcome to Polo")

    print("Import config")
    config = PoloConfig()
    config.read_ini('config.ini')
    trials = config.get_trial_names()

    print("Pick a trial")
    print(trials)

    print("Initialize corpus")
    corpus = PoloCorpus(config)
    corpus.cache_mode = True

    print("Importing stopwords")
    corpus.import_table_stopword(use_nltk=True)

    print("Importing doc")
    corpus.import_table_doc()

    print("Importing doctoken")
    corpus.add_table_doctoken() # FAILS ON cache_mode=True !

    print("Importing token")
    corpus.add_table_token()

    print("Importing bigrams")
    corpus.add_tables_ngram_and_docngram(n=2)

    config.import_ini(trials[0])

    print("Initializing")
    mallet = PoloMallet(config)
    mallet.cache_mode = True

    print('Importing corpus')
    mallet.mallet_import()

    print('Training model')
    mallet.mallet_train()

    print("Putting data into database")
    mallet.tables_to_db()

    print("Adding diagnostics tables")
    mallet.add_diagnostics()

    print("Adding doc table with topic entropy")
    mallet.add_topic_entropy()

    print("Adding topicpair table")
    mallet.create_table_topicpair()

    print("Cleaning up")
    #mallet.del_mallet_files()

    print("Done with", mallet.config.trial_name)
